### ISSUE TITLE
Error: Creating product

### ISSUE THREAD

**Issue by paarce** [jhonr1vera/rest-api-express#2]
<img width="888" alt="Screenshot 2024-01-10 at 22 41 55" src="https://github.com/jhonr1vera/rest-api-express/assets/11846967/608d6413-205d-4ecc-8546-24a7d819ec8a">
<img width="1289" alt="Screenshot 2024-01-10 at 22 41 45" src="https://github.com/jhonr1vera/rest-api-express/assets/11846967/3a280b47-e31c-4d66-b523-e8b784118ef2">

```
/Users/augustoc.p./Development/rest-api-express/scr/controllers/controllers.js:11
            if(err) throw err;
                    ^

Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/Users/augustoc.p./Development/rest-api-express/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/Users/augustoc.p./Development/rest-api-express/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/Users/augustoc.p./Development/rest-api-express/node_modules/mysql/lib/Connection.js:198:25)
    at controller.list (/Users/augustoc.p./Development/rest-api-express/scr/controllers/controllers.js:10:19)
    at Layer.handle [as handle_request] (/Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/layer.js:95:5)
    at /Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/augustoc.p./Development/rest-api-express/node_modules/express/lib/router/index.js:346:12) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```

Note: The issue might be ease to track if you see the console, but there is no error view for the users

**Comment by jhonr1vera** [comment]
I looked at the error but did not find it (even in both consoles, server and user), maybe it was an error from the table parameters
![Captura de pantalla 2024-01-16 1903531](https://github.com/jhonr1vera/rest-api-express/assets/122948173/f02d99b8-2426-4716-9c90-ea3514ec6a0e)

**Comment by paarce** [comment]
I don't get why this random product detail is shown on the left side taking most of the space in the screen and then the real product that I have selected is shown on the right side @jhonr1vera 

https://github.com/jhonr1vera/rest-api-express/assets/11846967/c44e0315-9d1d-4a15-8b30-7ab391ee7ba1

**Comment by paarce** [comment]
I was able to found the issue, and it was because by the time I. tried to create the product the DB was no properly created, but there was no error real message for the user. Now that you have the popup it's clear when an error happens
